{
    "name": "TextInputWidget",
    "version": "1.0.16",
    "icon": "fas fa-keyboard",
    "category": "automation",
    "author": "philipp2310",
    "maintainers": [
        "Psycho"
    ],
    "desc": "Gives you a widget with direct text input for alice.",
    "aliceMinVersion": "1.0.0-b3",
    "systemRequirements": [],
    "pipRequirements": [],
    "conditions": {
        "lang": [
            "en",
            "de",
            "fr"
        ]
    }
}